### ISSUE TITLE
Missing fields

### ISSUE THREAD

**Issue by tobia** [bootprint/bootprint-openapi#53]
Some very important fields seem to be missing from the Handlebars templates, such as `host` and `basePath`.

Unless this is "a feature not a bug", I will add them and submit a pull request.

**Comment by nknapp** [comment]
You are right. These fields are indeed missing. They weren't really important for my use-cases but they should be in there. PR is welcome. Would be great if a test-case was included.

**Comment by nknapp** [comment]
I am wondering: I just made a commit for #52 and would make a release now. If you tell me that you have it done within the next our, I would defer the release until you are done, so you don't have to rebase everything again.

**Comment by tobia** [comment]
No, please go ahead. I'm writing a full API specification and I will add all the fields I find missing. PR will be coming in a few days (hopefully)

**Comment by nknapp** [comment]
ok, fine. Thanks for your help.

**Comment by TheTaylorHicks** [comment]
Pull request https://github.com/bootprint/bootprint-openapi/pull/71 addresses this issue by adding basePath to the generated documentation. Host has been omitted, citing the design of Swagger UI as a design precedent. 

If you still think the omission of host requires attention, please open a new issue.
