### ISSUE TITLE
Weird generate behaviour

### ISSUE THREAD

**Issue by koen-serry** [bootprint/bootprint-openapi#67]
Hi,

I was trying to integrate the bootprint-openapi into grunt, but I encounter something weird.

Running watch works perfectly, however I get a state pending while running through generate. Which isn't awaiting termination I think.

```javascript
    require('bootprint').load(require('bootprint-openapi'))
       .merge({handlebars: { templates: "api/templates",partials: "api/partials" }})
      .build('../swagger.yml','./apidocs')
      .generate()
      .done(console.log)

Ouputs : 

Loading bootprint-openapi 0.16.0
Loading bootprint-json-schema 0.8.6
Loading bootprint-base 0.7.2
{ state: 'pending' }
```

Is there any way I could await termination before returning?

Thx

**Comment by nknapp** [comment]
I've had similar errors with mocha a couple of times. Have you declared your grunt tasks asynchronous (using `var done = this.async()` as describe [here](http://gruntjs.com/creating-tasks))?
`grunt` may force the process to exit when it is done. And if you don't declare your task "async", it just does not know that the task is still running. 
Although this does not explain your example output. Have you run this example stand-alone (only this code in a single file)? NodeJS shouldn't exit the process if a promise is still waiting to be resolved in the event loop.

**Comment by koen-serry** [comment]
the "var done = this.async()" did the trick, but it did exit the event loop. Although I didn't know there was something preventing nodejs from exiting if a promise was still pending.

**Comment by nknapp** [comment]
If you write a file containing only the following line

```js
setTimeout(() => console.log("done"),1000
```
You will get the output "done" after on second. Pending promises are actually the same thing if you have called `.then()` or `.done()` with a callback function. 
A program containing only:

```js
require('q').delay(1500)
    .done(() => console.log("done with promise"))
```
will also not quit until the "done with promise" is logged.
That's why I would like to know: Have you put only the lines (and no more than)

```js
require('bootprint').load(require('bootprint-openapi'))
       .merge({handlebars: { templates: "api/templates",partials: "api/partials" }})
      .build('../swagger.yml','./apidocs')
      .generate()
      .done(console.log)
```

into the file when you saw the `{ state: 'pending' }` output? Or was it as part of the grunt-task?
