### ISSUE TITLE
Invalid spaces in style names causes IE not to load styles

### ISSUE THREAD

**Issue by gkidder** [bootprint/bootprint-openapi#68]
Due to invalid spaces in the names of some styles, IE is not loading those styles. (IE 9+ is apparently stricter for styles.)
Example:
index.htm file has this:
class="swagger--panel-operation-post panel"
main.css has this style:
swagger--panel-operation-post
It appears that the script that generates the css ignores anything after the space in the class name ' panel'

**Comment by nknapp** [comment]
That is strange. `class="swagger--panel-operation-post panel"` means that element has two classes: `swagger--panel-operation-post` and `panel`.
According two the Bootstrap documentation, [panels get two classes](https://getbootstrap.com/components/#panels). 
The only difference between the Bootstrap docs and your example is the order of the classes within the `class`-attribute.
Could you try manually replacing the class with `class="panel swagger--panel-operation-post"` and see if it makes a difference?

**Comment by gkidder** [comment]
Thanks for the reply. I think I did not understand that syntax. The problem is that the stylesheet does not load in IE when the files are served from the server. (It loads fine when loaded locally.) I have tried several things to correct it and I thought it was a style naming issue. The problem seems to be with the table formats which look like this:

[cid:image002.jpg@01D1A6D6.F20FA9E0]
In Chrome it looks like this:
[cid:image003.jpg@01D1A6D6.F20FA9E0]

It looks fine in Chrome and Firefox, but not IE 11. Several things are missing: the table background color, cell padding, the headers “DESCRIPTION”, “REQUEST PARAMETERS” and “RESPONSES” heads, the column heads on the request parameter table….

FYI, I’m not a coder, but a tech writer using Bootprint to generate html documentation from our yaml api descriptions. Do you have an idea what is wrong?
I am loading the page inside an iframe, if that makes any difference.


Thanks,


Gayle Kidder
Product Team & Services
Enviance | www.enviance.com<http://www.enviance.com/>
Office: (760) 296 0200 ext 168 | Mobile: (619) 851 9064

**Comment by nknapp** [comment]
I cannot see the screenshots, but it sounds like the browser is unable to download the `main.css` file from the server. Can you make sure it is there? You could also [inline the styles](https://github.com/bootprint/bootprint-openapi#create-a-single-file) and create a single HTML file to make sure that no style-information is missing. This would also make it easier for people to save the docs locally.

iframes shouldn't be a problem. https://bootprint.knappi.org uses iframes too.

**Comment by gkidder** [comment]
I did try your suggestion below and it did not fix it.

manually replacing the class with class="panel swagger--panel-operation-post"


From: Kidder, Gayle
Sent: Thursday, May 05, 2016 2:04 PM
To: 'bootprint/bootprint-openapi' <reply@reply.github.com>
Subject: RE: [bootprint/bootprint-openapi] Invalid spaces in style names causes IE not to load styles (#68)

Thanks for the reply. I think I did not understand that syntax. The problem is that the stylesheet does not load in IE when the files are served from the server. (It loads fine when loaded locally.) I have tried several things to correct it and I thought it was a style naming issue. The problem seems to be with the table formats which look like this:

[cid:image001.jpg@01D1A6DB.7F7137F0]
In Chrome it looks like this:
[cid:image002.jpg@01D1A6DB.7F7137F0]

It looks fine in Chrome and Firefox, but not IE 11. Several things are missing: the table background color, cell padding, the headers “DESCRIPTION”, “REQUEST PARAMETERS” and “RESPONSES” heads, the column heads on the request parameter table….

FYI, I’m not a coder, but a tech writer using Bootprint to generate html documentation from our yaml api descriptions. Do you have an idea what is wrong?
I am loading the page inside an iframe, if that makes any difference.


Thanks,


Gayle Kidder
Product Team & Services
Enviance | www.enviance.com<http://www.enviance.com/>
Office: (760) 296 0200 ext 168 | Mobile: (619) 851 9064

**Comment by gkidder** [comment]
There is no problem finding the stylesheet. Some of the styles do display, Just not all of them.
![chrome](https://cloud.githubusercontent.com/assets/12503481/15058196/c1c676d2-12cf-11e6-876e-74c616b398fa.png)
![ie11](https://cloud.githubusercontent.com/assets/12503481/15058202/ca4d37b4-12cf-11e6-964b-de44e513a463.png)

**Comment by nknapp** [comment]
Could you try if http://petstore.swagger.io.bp.knappi.org/v2/swagger.json.html looks wrong as well? So far, I haven't been able to reproduce the problem. I tried https://netrenderer.de/ to render this URL in IE11, but it looks fine.

**Comment by gkidder** [comment]
Same browser, this is what petstore looks like. Looks like it's ok there. 

![image](https://cloud.githubusercontent.com/assets/12503481/15059274/5f0a5066-12d6-11e6-9c69-0adf9a9b32df.png)

**Comment by gkidder** [comment]
I tried netrenderer with my page and it does reproduce the problem. Page is: https://go.enviance.com/AppHelp/RestAPI/default.htm

**Comment by gkidder** [comment]
Thanks for your help. I determined that 1) I had the wrong DOCTYPE declaration for html 5 and 2) there's still an IE issue related to what browser version it defaults to. When the page is served locally or on the intranet, the default IE version is Edge (11). When served over the Internet the default mode is IE5, possibly due to server setting.

**Comment by nknapp** [comment]
"I had the wrong DOCTYPE declaration" means you changed it manually? Or is there something that should be improved in `bootprint`. Otherwise I would close this issue.
