### ISSUE TITLE
Output of `security` definition not quite complete.

### ISSUE THREAD

**Issue by nknapp** [bootprint/bootprint-openapi#7]
The petstore-example still prints out an [Object object] or something like that. If someone has a good idea of how to format this tag, please tell me.

**Comment by Sauradyuti** [comment]
I'm currently working on this. I'll let you know once I get it working.

**Comment by nknapp** [comment]
Cool, that's one of the last things missing for a complete spec support. It would be great if you wrote testcases as well, like the others in the `test/` directory to verify the output. I think the tests could be better, but at least they verify that certain elements and texts are present in the output. There should be tests for every new feature and every bugfix.

**Comment by nknapp** [comment]
@Sauradyuti. Are you still working on this issue? If you need any help, just let me now. Sometimes, I'm in the `#bootprint` channel on freenode (IRC), but probably not before 22:30 GMT.
