### ISSUE TITLE
how to get the same style with the swagger html page?

### ISSUE THREAD

**Issue by jinwyp** [bootprint/bootprint-openapi#70]
I just clone the whole project and run the example.js

I found that the style of  target/index.html  is different from http://petstore.swagger.io/ page. 

the official http://petstore.swagger.io/ page have  "Show/Hide / List Operations / Expand Operations "  which is more convenient to nav the API , 

How to do this? How to change the theme?

**Comment by nknapp** [comment]
* You can override styles and partials as you like (described here: https://github.com/bootprint/bootprint/blob/master/doc/config.md)
* You an write your own configuration module to encapsulate your adaptions (described here: https://github.com/bootprint/bootprint/blob/master/doc/modules.md)
* At the moment, you **cannot** include any external JavaScript files. You could use inline-scripts for your interactions thought. That would require a [customize](https://github.com/bootprint/customize)-engine for JS which does not exist yet. I thought about writing an adapter for browserify or something like that.

If you are planning to do anything that improves the general usability of this project, I would gladly accept a pull-request or invite your to the team. Sadly, I don't have much time to do anything for the project right now, but I **will** publish new versions quickly when new features or bugfixes are available.

**Comment by nknapp** [comment]
Also, have a look on this [tree of hbs-partials](https://github.com/bootprint/bootprint-openapi/blob/master/handlebars-partials.md) to find the right partials to override or change.

**Comment by jinwyp** [comment]
many thanks
