### ISSUE TITLE
Change default behavior multiline examples have newlines replaced by "\n"

### ISSUE THREAD

**Issue by Herst** [bootprint/bootprint-openapi#77]
Especially for code it would be nicer if per default newlines in the source of `example:`s would be displayed as-is, maybe differentiating between explicit ones and those just for word-wrap purposes. (Additionally maybe have no word-wrapping itself and display it in an element with scrollbars).

**Comment by nknapp** [comment]
Could you provide an example spec that shows the behavior in the [playground](http://bootprint.knappi.org/) and then describe what you would expect. I'm not sure I fully understand what you mean, but it may be impossible to achieve since the JSON is parsed before processing, removing all line-break information.

**Comment by Herst** [comment]
Testcase:
```yaml
---
swagger: '2.0'
info:
  version: 0.0.0
  title: Simple API
paths:
  /:
    get:
      parameters:
      - name: body
        in: body
        schema:
          type: string
          example: >
              1
              foo
              
              bar
      responses:
        200:
          description: OK
          schema:
            type: string
            example: >
              2
              foo
              
              bar
```

**Comment by nknapp** [comment]
I just noticed that the example-syntax is not treated correctly by bootprint-openapi: [The spec tells us](https://github.com/OAI/OpenAPI-Specification/blob/master/versions/2.0.md#exampleObject) to use an object with the mime-type as key to specify examples for different mime-types.

Examples for "text/plain" or other "text/*" mime-types could be displayed like you suggest, but for a examples for "application/json" '\n' is the correct way to show newlines.

**Comment by Herst** [comment]
But for `application/json` only inside strings, right?

**Comment by nknapp** [comment]
Yes, but what you have there *is* a string.

**Comment by Herst** [comment]
I just realized that an example does not have to be a string, somehow I misunderstood that.
