### ISSUE TITLE
Support for XML in response examples

### ISSUE THREAD

**Issue by luileito** [bootprint/bootprint-openapi#81]
I'd like to display both JSON and XML examples, like in this snippet:
```
  ...
  responses:
    200:
      examples:
        application/json:
          data: false
          code: 9001
        application/xml: |
          <root>
            <data>false</data>
            <code>9001</code>
          </root>
```
However, the output is parsed as a raw string:
```
"<root>\n  <data>false</data>\n  <code>9001</code>\n</root>\n"
```

This issue is somehow related to #37 (no XML is displayed) and #77 (newlines are not removed).

**Comment by nknapp** [comment]
This has now landed in bootprint-openapi@0.17.1
