### ISSUE TITLE
Is there any use for the Javascript (parts of Bootstrap)?

### ISSUE THREAD

**Issue by Herst** [bootprint/bootprint-openapi#86]
I couldn't find any.

**Comment by nknapp** [comment]
It is a preparation for implementing interactive features (#29, #51). And in theory, if you have made customizations to the templates, you can use these library yourself. 

But if you are saying "it should not be in there if it's not used" I understand your point. I could have left it out of the 1.0 release.

Do you need an option to remove it?

**Comment by Herst** [comment]
Not necessarily, I can remove it myself in some script, I am already running quite a few ones over it in order to create a small and standalone document out of it.
