### ISSUE TITLE
Stronger color scheme

### ISSUE THREAD

**Issue by celsom3** [bootprint/bootprint-openapi#89]
This is a suggestion. I noticed that the resulting HTML could be improved by using a stronger color scheme, just to make it a bit more intuitive to follow.

The current colors used are a bit washed out, hardly noticeable.

It seems the change is simple enough. I simply added more saturation to the colors in the `theme.less` file and I got this result:

![screen shot 2017-02-13 at 1 41 20 pm](https://cloud.githubusercontent.com/assets/3922985/22902467/5f2916ee-f1f2-11e6-870d-5a5f11fdb3fb.png)

I would be glad to submit a PR is this is useful.

Another way to go about would be allow passing in options for colors.

**Comment by nknapp** [comment]
Hi. On the first glance this looks good. Maybe it is slighty too dark for the blue font-color of the tags.
I'm not an accessibility expert, but the tags should be well-readable, but maybe the font-color of the tags can be changed as well.
That is my only concern, but if you can make sure that there is enough contrast in the tags, I would accept a PR.

As for the "passing options": You can always override the styles with your own less files (see [this documentation about configuration files](https://github.com/bootprint/bootprint/blob/master/doc/config.md#providing-themes-with-custom-less-files) and [this CLI reference on how to use them](https://github.com/bootprint/bootprint/blob/master/doc/cli.md#command-line-usage) (it's the `-f` option.
Also have a look at the examples: [here](https://github.com/bootprint/bootprint-examples) and [here](https://github.com/bootprint/bootprint-examples/tree/master/config-file)

**Comment by celsom3** [comment]
Thanks! That actually resolves the issue. If I can override the using my own less files, that works for me. I should have read more of the documentation.

And yes, the legibility would be an issue. In my solution, I simply doubled down on the color and made it more intense/dark, and then changed the color of the content inside `.panel-title` and tags to be white.

I can submit a PR and leave it up to you. It's more of a matter preference on this, really.

![screen shot 2017-02-13 at 3 48 52 pm](https://cloud.githubusercontent.com/assets/3922985/22906911/fae19366-f203-11e6-8515-d70a4a4c466b.png)

Thanks for the help!

**Comment by nknapp** [comment]
Yeah, overriding styles was one of the main reasons for starting the project in the first place. 
Maybe I'll just play around the styles some more. I actually like the stronger background, but your last screenshot is a bit exhausting for my eyes as well. This is a difficult topic...
