### ISSUE TITLE
Bootprint is flipping JSON order

### ISSUE THREAD

**Issue by connorcook** [bootprint/bootprint-openapi#96]
Hi there-

I don't mean to complain about a relatively small issue, but for awhile I've noticed that using bootprint (and bootprint-openapi) flips the ordering of the JSON object properties in my "examples" (while retaining the proper order everywhere else). I know that technically JSON is orderless, but for my users, it's kind of a nuisance to have to puzzle out the order of the examples when it's the exact inverse of the actual output and the properties list that is immediately below it.

Here's a simple example: you can see the proper order below the example. This happens for all of my structures. The order in the "properties" list is correct, but the example is completely flipped.
![image](https://user-images.githubusercontent.com/5090543/31240982-43ce97ac-a9b7-11e7-9e18-f08ddfa559e9.png)

In larger and more complex objects, the effect is disorienting. Nested objects are affected in the same way, so each sub-object inside an example is also flipped.

I'm using bootprint-openapi at v1.1.0 and bootprint at 1.0.0. This also occurred in bootprint-swagger.

Here is my usage:

```
gulp.task('build-v1-docs', function() {
  return require('bootprint').load(require('bootprint-openapi'))
    .merge({ /* Any other configuration */ })
    .build('docs/swagger.json','docs')
    .generate();
});
```

**Comment by nknapp** [comment]
Hi and thanks for bringing this up. The examples are rendered using the "json-stable-stringify" package, which means that keys are alphabetically sorted.
This was actually meant to render JSON in a predictable and stable order, but I can see that this is not optimal in your.
We could use JSON.stringify instead, but I am not sure that this will have the desired effect.

**Comment by connorcook** [comment]
I see. If it was the best choice for the package, I totally understand. If nothing else, understanding that it's done in alphabetical order allows me to account for that when I run it through bootprint.

 Thank you for clarifying that behavior!

**Comment by darkprisco** [comment]
So,  how to avoit that json ordering using bootprint?
