### ISSUE TITLE
Generated HTML page looks nothing like example

### ISSUE THREAD

**Issue by tomrep** [bootprint/bootprint-openapi#97]
Hi,

I'm trying to generate HTML for my swagger.json, but the page generated looks nothing like what I see in example. I also tried generating HTML from example json, but it still looks like styles are missing.

$ bootprint openapi http://petstore.swagger.io/v2/swagger.json target
Loading bootprint-openapi 1.1.0
Loading bootprint-json-schema 1.1.0
Loading bootprint-base 1.1.0
[ 'target/index.html',
  'target/main.css',
  'target/main.css.map',
  'target/bundle.js',
  'target/bundle.js.map' ]

this is what I see in console log
But result looks like this:

<img width="1354" alt="screen shot 2018-08-08 at 08 15 46" src="https://user-images.githubusercontent.com/22789831/43819490-61f56d3c-9ae3-11e8-8a54-bd7ec79e9bf3.png">

<img width="1287" alt="screen shot 2018-08-08 at 08 16 06" src="https://user-images.githubusercontent.com/22789831/43819491-620f21dc-9ae3-11e8-8fb8-cd0add0748b1.png">

**Comment by nknapp** [comment]
Which example do you mean? I mean: What is the example that looks different from your output? As far as I can see, the output looks good.

**Comment by tomrep** [comment]
I was expecting styles and functionality that is shown here : http://petstore.swagger.io/ , but maybe I just misunderstood what the module does

**Comment by nknapp** [comment]
Bootprint was meant more for a printable documentation, although I think no spec ever got printed.
But the goal was to generate docs that can be watched in the browser and send it to someone.

What you are looking for is [swagger-ui](https://swagger.io/tools/swagger-ui/), I believe.
