### ISSUE TITLE
Link to app playground not resolved

### ISSUE THREAD

**Issue by andresoviedo** [bootprint/bootprint-openapi#98]
Thanks.  

FYI. This link is not being resolved.  However, it would be nice to have screenshots as well.

> Check this out: You can now try out the new bootprint-openapi playground. Just paste a OpenAPI-specification and make it readable.

http://bootprint.knappmeier.de/

**Comment by nknapp** [comment]
Oh, should be https://bootprint.knappi.org

**Comment by nknapp** [comment]
thanks, fixed it
